CREATE DATABASE work; 
USE work; 
CREATE TABLE employees ( 
emp_no INT NOT NULL PRIMARY KEY, 
birth_date DATE NOT NULL, 
first_name VARCHAR(20) NOT NULL, 
last_name VARCHAR(20) NOT NULL, 
gender CHAR NOT NULL, 
hire_date DATE NOT NULL ); 


CREATE TABLE salaries2 ( 
emp_no INT NOT NULL, 
salary INT NOT NULL, 
from_date DATE NOT NULL, 
to_date DATE NOT NULL, 
PRIMARY KEY (emp_no, from_date) 
) 
PARTITION BY RANGE (YEAR(from_date)) 
( PARTITION P1 VALUES LESS THAN (1984), 
PARTITION P2 VALUES LESS THAN (1985), 
PARTITION P3 VALUES LESS THAN (1986), 
PARTITION P4 VALUES LESS THAN (1987), 
PARTITION P5 VALUES LESS THAN (1988), 
PARTITION P6 VALUES LESS THAN (1989), 
PARTITION P7 VALUES LESS THAN (1990), 
PARTITION P8 VALUES LESS THAN (1991), 
PARTITION P9 VALUES LESS THAN (1992), 
PARTITION P10 VALUES LESS THAN (1993), 
PARTITION P11 VALUES LESS THAN (1994), 
PARTITION P12 VALUES LESS THAN (1995), 
PARTITION P13 VALUES LESS THAN (1996), 
PARTITION P14 VALUES LESS THAN (1997), 
PARTITION P15 VALUES LESS THAN (1998), 
PARTITION P16 VALUES LESS THAN (1999), 
PARTITION P17 VALUES LESS THAN (2000), 
PARTITION P18 VALUES LESS THAN (2001), 
PARTITION P19 VALUES LESS THAN MAXVALUE ); 

CREATE TABLE titles2 
( emp_no INT NOT NULL, 
title VARCHAR(50) NOT NULL, 
from_date DATE NOT NULL, 
to_date DATE NOT NULL, 
PRIMARY KEY (emp_no, title, from_date) ) 
PARTITION BY RANGE (YEAR(from_date)) 
( PARTITION P1 VALUES LESS THAN (1984), 
PARTITION P2 VALUES LESS THAN (1985), 
PARTITION P3 VALUES LESS THAN (1986), 
PARTITION P4 VALUES LESS THAN (1987), 
PARTITION P5 VALUES LESS THAN (1988), 
PARTITION P6 VALUES LESS THAN (1989), 
PARTITION P7 VALUES LESS THAN (1990), 
PARTITION P8 VALUES LESS THAN (1991), 
PARTITION P9 VALUES LESS THAN (1992), 
PARTITION P10 VALUES LESS THAN (1993), 
PARTITION P11 VALUES LESS THAN (1994), 
PARTITION P12 VALUES LESS THAN (1995), 
PARTITION P13 VALUES LESS THAN (1996), 
PARTITION P14 VALUES LESS THAN (1997), 
PARTITION P15 VALUES LESS THAN (1998), 
PARTITION P16 VALUES LESS THAN (1999), 
PARTITION P17 VALUES LESS THAN (2000), 
PARTITION P18 VALUES LESS THAN (2001), 
PARTITION P19 VALUES LESS THAN MAXVALUE ); 

CREATE TABLE dept_emp (
emp_no INT NOT NULL, 
dept_no VARCHAR(4) NOT NULL, 
from_date DATE NOT NULL, 
to_date DATE NOT NULL, 
FOREIGN KEY (emp_no) REFERENCES employees (emp_no), 
FOREIGN KEY (dept_no) REFERENCES departments (dept_no) ); 

CREATE TABLE departments ( 
dept_no VARCHAR(4) NOT NULL PRIMARY KEY, 
dept_name VARCHAR(50) NOT NULL ); 

CREATE TABLE dept_manager ( 
emp_no INT NOT NULL, 
dept_no VARCHAR(4) NOT NULL, 
from_date DATE NOT NULL, 
to_date DATE NOT NULL, 
FOREIGN KEY (emp_no) REFERENCES employees (emp_no), 
FOREIGN KEY (dept_no) REFERENCES departments (dept_no) ); 

SET profiling = 1; select * from salaries where from_date > '1990-12-31' and from_date < '1991-12-31'; SHOW PROFILES;


